import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/router";
import { useAuth } from "../lib/auth";
import type { Role } from "../lib/types";
const roles: Role[] = ["BUYER", "REAL_ESTATE_AGENT", "LEGAL_REVIEWER", "FINANCIAL_INSTITUTION"];
export default function LoginPage() {
  const { login, register } = useAuth(); const router = useRouter();
  const [mode, setMode] = useState<"login" | "register">("login"); const [fullName, setFullName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [role, setRole] = useState<Role>("BUYER"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { if (router.pathname === "/registration" || router.query.mode === "register") setMode("register"); }, [router.pathname, router.query.mode]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { if (mode === "login") { await login(email, password); router.push("/dashboard"); } else { await register({ fullName, email, password, role }); setMode("login"); setError("Registration complete. Sign in to continue."); } } catch (e) { setError(e instanceof Error ? e.message : "Unable to complete request."); } finally { setBusy(false); } }
  return <main className="auth-page"><div className="auth-aside"><span className="eyebrow">PROPERTY INTELLIGENCE</span><h1>Make confident real estate decisions.</h1><p>One workspace for verified property facts, risk assessment and actionable due diligence.</p></div><section className="auth-card"><div className="brand large">Due<span>Diligence</span></div><h2>{mode === "login" ? "Welcome back" : "Create your account"}</h2><p className="muted">{mode === "login" ? "Sign in to access your workspace." : "Start reviewing properties with your team."}</p><form onSubmit={submit}>{mode === "register" && <label>Full name<input required value={fullName} onChange={e => setFullName(e.target.value)} /></label>}<label>Email<input required type="email" value={email} onChange={e => setEmail(e.target.value)} /></label><label>Password<input required minLength={8} type="password" value={password} onChange={e => setPassword(e.target.value)} /></label>{mode === "register" && <label>Role<select value={role} onChange={e => setRole(e.target.value as Role)}>{roles.map(item => <option key={item} value={item}>{item.replaceAll("_", " ")}</option>)}</select></label>}<button className="primary-button" disabled={busy}>{busy ? "Working…" : mode === "login" ? "Sign in" : "Create account"}</button></form>{error && <p className="form-message" role="alert">{error}</p>}<button className="link-button switch" onClick={() => { setMode(mode === "login" ? "register" : "login"); setError(""); }}>{mode === "login" ? "Need an account? Register" : "Already registered? Sign in"}</button></section></main>;
}
